project:
  type: website

website:
  title: "Hampton Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



