project:
  type: website

website:
  title: "Hampton Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - docs/people.qmd
      - docs/projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



