project:
  type: website
  output-dir: "/Users/bcdemattei/Desktop/Projects/Hampton-Lab/docs"
  
website:
  title: "Hampton Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - projects.qmd
  page-footer: 
    left: |
      [![](images/CISlogo.png){fig-alt="Carnegie Science" width=65px}](https://www.carnegiescience.edu)     
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



