project:
  type: website
  output-dir: "/Users/bcdemattei/Desktop/Projects/Hampton-Lab/docs"
  
website:
  title: "Hampton Lab"
  favicon: images/roti_logo.png
  navbar:
    logo: images/roti_logo.png
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - projects.qmd
      - news.qmd
    
  page-footer: 
    left: |
      [![](images/TERC.png){fig-alt="UC Davis Tahoe Environmental Research Center" width=150px}](https://tahoe.ucdavis.edu)
      201 Country Club Dr. Incline Village, NV 89451
      
    right:
      - text: Contact
        href: contact.qmd
      - icon: twitter
        href: https://bsky.app/profile/sehampton.bsky.social
      - icon: github
        href: https://github.com/Hampton-Lab
        aria-label: Hampton Lab GitHub
        

    center: | 
      | Background Image of Lake Baikal Credit: [Andrei Chuganov](https://commons.wikimedia.org/wiki/File:Baikal_140629_0179.jpg#metadata)
      |  
      |   _Keratella serrulata_ Logo Credit: [Thomas G](https://commons.m.wikimedia.org/wiki/File:Keratella_serrulata_253892773.png) |
    
format:
  html:
    theme: 
      light: 
        flatly
      dark:
        flatly
    css: styles.css
    toc: true
    linkcolor: white
    



