---
title: "Stephanie Hampton"
subtitle: "List of Publications"
format: html
---
## Peer Reviewed

| Sharma, S., S.E. Hampton, and I.A. Kimirei. In press. Inland Waters: The Future of Limnology is Interdisciplinary, Collaborative, Inclusive, and Global. Chapter 31 in Wetzel’s Limnology, 2nd edition. 
|
| Brousil, M.R., et al. 2023. Improving ecological data science with workflow management software. Methods in Ecology & Evolution.
|
| Hampton, S.E., S. Sharma, M. Brousil and A. Filazzola. 2022. Winter and summer storms modify chlorophyll relationships with nutrients in seasonally ice-covered lakes. Ecosphere 13(11): e4272.
|
| Meyer, M. F.; Ozersky, T.; Woo, K. H.; Shchapov, K.; Galloway, A. W. E.; Schram, J. B.; Rosi, E. J.; Snow, D. D.; Timofeyev, M. A.; Karnaukhov, D. Yu.; Brousil, M. R.; Hampton, S. E. 2022. Effects of spatially heterogeneous lakeside development on nearshore biotic communities in a large, deep, oligotrophic lake (Lake Baikal, Siberia). Limnology and Oceanography 67: 2649–2664.
| 
| Powers, S. M., S. C. Fradkin, W. Baccus, C. Archambault, J. R. Boetsch, M. R. Brousil, R. Lofgren, A. Rawhouser, and S. E. Hampton. 2022. Summer ecosystem structure in mountain lakes linked to interannual variability of lake ice, snowpack, and landscape attributes. Limnology and Oceanography 67(9): 2073-2087.
| 
| Sweeney, K., G. Rollwagen-Bollens, and S.E. Hampton. 2022. Grazing impacts of rotifer zooplankton on a cyanobacteria bloom in a shallow temperate lake (Vancouver Lake, WA, USA). Hydrobiologia: 849: 2683–2703.
| 
| Meyer, M. F., et al. 2022. A unified dataset of colocated sewage pollution, periphyton, and benthic macroinvertebrate community and food web structure from Lake Baikal (Siberia). Limnology and Oceanography Letters 7:62–79.
| 
| Cavaliere, E., I. B. Fournier, V. Hazuková, G. P. Rue, S. Sadro, et al. 2021. The Lake Ice Continuum Concept: Influence of Winter Conditions on Energy and Ecosystem Dynamics. Journal of Geophysical Research: Biogeosciences 126:e2020JG006165.
| 
| Ozersky, T., et al. 2021. The Changing Face of Winter: Lessons and Questions From the Laurentian Great Lakes. Journal of Geophysical Research: Biogeosciences 126:e2021JG006247.
| 
| Hackett, E. J., et al. 2021. Do synthesis centers synthesize? A semantic analysis of topical diversity in research. Research Policy 50:104069.
| 
| Ozersky, T., et al. 2021. Hot and sick? Impacts of warming and a parasite on the dominant zooplankter of Lake Baikal. Limnology and Oceanography. Online Early.
| 
| Akerlof, K. L., et al. 2021. Categorizing Professionals’ Perspectives on Environmental Communication with Implications for Graduate Education. Environmental Communication 0:1–18.
| 
| Wollrab, S., Izmest’yeva, L.R., Hampton, S.E., Silow, E., Litchman, E., and C.A. Klausmeier. 2021. Climate change-driven regime shifts in a planktonic food web. American Naturalist 197: 281–295
| 
| Dexter, E., S. L. Katz, S. M. Bollens, G. Rollwagen-Bollens, and S. E. Hampton. 2020. Modeling the trophic impacts of invasive zooplankton in a highly invaded river. PLOS ONE 15:e0243002.
| 
| Sharma, S., et al. 2020. Integrating Perspectives to Understand Lake Ice Dynamics in a Changing World. Journal of Geophysical Research: Biogeosciences 125(8): e2020JG005799.
| 
| Thackeray, S. J., and S. E. Hampton. 2020. The case for research integration, from genomics to remote sensing, to understand biodiversity change and functional dynamics in the world’s lakes. Global Change Biology 26: 3230-3240.
| 
| Katz, S. L., J. C. Padowski, M. Goldsby, M. P. Brady, and S. E. Hampton. 2020. Defining the Nature of the Nexus: Specialization, Connectedness, Scarcity, and Scale in Food–Energy–Water Management. Water 12:972.
| 
| Katz, S. L., K. A. Barnas, M. Diaz, and S. E. Hampton. 2019. Data system design alters meaning in ecological data: salmon habitat restoration across the U.S. Pacific Northwest. Ecosphere10:e02920.
| 
| Meyer, M. F., S. M. Powers, and S. E. Hampton. 2019. An Evidence Synthesis of Pharmaceuticals and Personal Care Products (PPCPs) in the Environment: Imbalances among Compounds, Sewage Treatment Techniques, and Ecosystem Types. Environmental Science & Technology53:12961–12973.
| 
| Powers, S. M., R. B. Chowdhury, G. K. MacDonald, G. S. Metson, A. H. W. Beusen, A. F. Bouwman, et al. 2019. Global opportunities to increase agricultural independence through phosphorus recycling. Earth’s Future, 7. https://doi.org/10.1029/2018EF001097
| 
| Hampton, S. E., M. D. Scheuerell, M. J. Church, and J. M. Melack. 2019. Long-term perspectives in aquatic research. Limnology and Oceanography64:S2–S10.
| 
| Block, B. D., B. A. Denfeld, J. D. Stockwell, G. Flaim, H. F. Grossart, L. B. Knoll, D. B. Maier, R. L. North, M. Rautio, J. A. Rusak, S. Sadro, G. A. Weyhenmeyer, A. J. Bramburger, D. K. Branstrator, K. Salonen, and S. E. Hampton. 2018. The unique methodological challenges of winter limnology. Limnol Oceanogr Methods. DOI: 10.1002/lom3.10295
| 
| Powers, S. M., and S. E. Hampton. 2019. Open science, reproducibility, and transparency in ecology. Ecological Applications: in press. DOI: 10.1002/eap.1822
| 
| Leech, D. M., A. I. Pollard, S. G. Labou, and S. E. Hampton. 2018. Fewer blue lakes and more murky lakes across the continental U.S.: Implications for planktonic food webs. Limnology and Oceanography: 63: 2661-2680. DOI: 10.1002/lno.10967
| 
| Frassl, M. A., et al. 2018. Ten simple rules for collaboratively writing a multi-authored paper. PLOS Computational Biology 14:e1006508.
| 
| Gray, D.K., S.E. Hampton, C.M. O’Reilly, S. Sharma and R.S. Cohen. 2018. How do data collection and processing methods impact the accuracy of long-term trend estimation in lake surface water temperatures? Limnology & Oceanography: Methods 16: 504–515. DOI: 10.1002/lom3.10262
| 
| Ozersky, T., E. A. Volkova, N. A. Bondarenko, O. A. Timoshkin, V. V. Malnik, V. M. Domysheva, and S. E. Hampton. 2018. Nutrient limitation of benthic algae in Lake Baikal, Russia. Freshwater Science: 37(3): 472-482.
| 
| Hampton, S. E., S. McGowan, T. Ozersky, S. G. P. Virdis, T. T. Vu, T. L. Spanbauer, B. M. Kraemer, G. Swann, A. W. Mackay, S. M. Powers, M. F. Meyer, S. G. Labou, C. M. O’Reilly, M. DiCarlo, A. W. E. Galloway, and S. C. Fritz. 2018. Recent ecological change in ancient lakes. Limnology & Oceanography: in press.
| 
| Denfeld, B.A., H.M. Baulch, P.A. del Giorgio, S.E. Hampton, J. Karlsson. 2018.  A synthesis of carbon dioxide and methane dynamics during the ice‐covered period of northern lakes Limnology & Oceanography Letters: DOI 10.1002/lol2.10079.
| 
| Hampton, S. E., and S. G. Labou. 2017. Careers in ecology: a fine-scale investigation of national data from the U.S. Survey of Doctorate Recipients. Ecosphere 8(12):e02031.
| 
| Powers, S.M. et al. 2017 Nitrification contributes to winter oxygen depletion in seasonally frozen forested lakes. Biogeochemistry (2017) 136: 119.
| 
| Powers, S.M., et al. 2017 Ice duration drives winter nitrate accumulation in north temperate lakes. Limnology & Oceanography Letters 2: 177–186.
| 
| Hampton, S.E., et al. 2017. Skills and knowledge for data-intensive environmental research. BioScience 67 (6): 546-557.
| 
| Baron, J.S., et al. 2017. Sustaining synthesis centers as critical research infrastructure. BioScience: 67 (8): 750-759.
| 
| Hampton, S.E. et al. (62 authors) 2017. Ecology under lake ice. Ecology Letters 20: 98-111. DOI: 10.1111/ele.12699. [Data; Code]
| 
| Meyer, M.F., S.E. Hampton, T. Ozersky, O.O. Rusanovskaya & K.H. Woo. 2017. Vulnerability of rotifers and copepod nauplii to predation by Cyclops kolensis (Crustacea, Copepoda) under varying temperatures in Lake Baikal, Siberia. Hydrobiologia 796: 309-318.
| 
| Jackson, S.T., C.S. Duke, S.E. Hampton, K.L. Jacobs, L.N. Joppa, K.S. Kassam, H.A. Mooney, L.A. Ogden, M. Ruckelshaus, J.F. Shogren. 2016. Policy Forum: Toward a national, sustained U.S. ecosystem assessment. Science 354:838-839.
| 
| Williams, J.J., M. Beutel, A. Nurse, B. Moore, S.E. Hampton, J.E. Saros. 2016. Phytoplankton responses to nitrogen enrichment in Pacific Northwest, USA Mountain Lakes. Hydrobiologia 776: 261–276. [Data; Supplementary Information]
| 
| Joppa, L.N., Boyd, J.W., Duke, C.S., Hampton, S., Jackson, S.T., Jacobs, K.L., Kassam, K.S., Mooney, H.A., Ogden, L.A., Ruckelshaus, M., and Shogren, J.F. 2016. Government: Plan for ecosystem services. Science 351: 1037–1037.
| 
| Izmest’eva, L.R., M.V. Moore, S.E. Hampton, C. J. Ferwerda, D.K. Gray, K.H. Woo, H. V. Pislegina, L. S. Krashchuk, S. V. Simaraeva, E.A. Silow. 2016. Lake-wide physical and biological trends associated with warming in Lake Baikal. J. Great Lakes Research 42: 6-17.
| 
| O’Reilly, C.M., S. Sharma, D.K. Gray, S.E. Hampton, et al. (64 authors). 2015. Rapid and highly variable warming of lakes around the globe. Geophysical | Research Letters 42:10,773–10,781. [WSU Press Release 16 Dec 2015] [CIRMOUNT Brevia overview May 2016]
| 
| Katz, S.L., L.R. Izmest’eva, S.E. Hampton, T. Ozersky, K. Shchapov, M.V. Moore, S.V. Shimaraeva and E.A. Silow. 2015. The “Melosira years” of Lake Baikal: Winter environmental conditions at ice onset predict under-ice algal blooms in spring. Limnology and Oceanography 60: 1950–1964.
| 
| Hampton, S.E., S. Anderson, S.C. Bagby, C. Gries, X. Han, E. Hart, M.B. Jones, W.C. Lenhardt, A. MacDonald, W. Michener, J.F. Mudge, A. Pourmokhtarian, M.P. Schildhauer, K.H. Woo, and N. Zimmerman. 2015. The Tao of open science in ecology. Ecosphere: 6:art120. http://dx.doi.org/10.1890/ES14-00402.1.
| 
| Sharma, S. et al. (75 authors) 2015. A global database of lake surface temperatures collected by in situ and satellite methods from 1985–2009. Scientific Data, 2: 150008. doi:10.1038/sdata.2015.8
| 
| Hampton, S.E., M.V. Moore, T. Ozersky, E.H. Stanley, C.M. Polashenski, and A.W.E. Galloway. 2015. Heating up a cold subject: prospects for under-ice plankton research in lakes. Journal of Plankton Research 37: 277–284.
| 
| Francis, T.B. E. Wolkovich, S.E. Hampton, M.D. Scheuerell, S.L. Katz, and E.E. Holmes. 2014. Shifting regimes and changing interactions in the Lake Washington, USA, plankton community from 1962–1994. PLoS ONE 9(10): e110363. doi:10.1371/journal.pone.0110363.
| 
| Langen, T.A., T. Mourad, B. Grant, W.K. Gram, B.J. Abraham, D.S. Fernandez, M. Carroll, A. Nuding, and S.E. Hampton. 2014. Opportunities and challenges in using large public data sets in the undergraduate ecology classroom. Frontiers in Ecology and the Environment 12: 362-363.
| 
| Anderson, S.S., et al. (24 authors) 2014. Understanding and properly interpreting the 2010 Deepwater Horizon Blowout. In: Oil Spill Remediation: Colloid Chemistry-Based Principles and Solutions (eds. Somasundaran, P., Farinato, R.S. & Papadopoulos, K.). John Wiley & Sons, Inc, pp. 19–57.
| 
| Hampton, S.E., D.K. Gray, L.R. Izmest’eva, M.V. Moore, and T. Ozersky. 2014. The rise and fall of plankton: long-term changes in the vertical distribution of algae and grazers in Lake Baikal, Siberia. PLoS ONE 9(2): e88920. doi:10.1371/journal.pone.0088920
| 
| Tewksbury, J.J., et al. (19 authors) 2014. Natural history’s place in science and society. BioScience 64(4): 300-310.
| 
| Hampton, S.E. 2013. Understanding lakes near and far. Science 342: 815-816.
| 
| Hampton, S.E., E.E. Holmes, D.E. Pendleton, L.P. Scheef, M.D. Scheuerell, and E.J. Ward. 2013. Quantifying effects of abiotic and biotic drivers on community dynamics with multivariate autoregressive (MAR) models. Ecology 94: 2663–2669.
| Supplemental R Script
| 
| Scheef, L.P., S.E. Hampton, and L.R. Izmest’eva. 2013. Inferring plankton community structure from marine and freshwater long-term data using multivariate autoregressive models. Limnology and Oceanography: Methods 11:475-484.
| 
| Hampton, S.E., C. Strasser, A. Batcheller, W. Gram, C. Duke, J. Tewksbury, and J. Porter. 2013. Big data and the future of ecology. Frontiers in Ecology and the Environment 11: 156–162.
| 
| Strasser, C.A. and S.E. Hampton. 2012. The Fractured Lab Notebook: Undergraduates and Ecological Data Management Training in the United States. Ecosphere3:art116.
| 
| Peterson, C.H. et al. 2012. A tale of two spills: novel science and policy implications of an emerging new oil spill model. BioScience 62: 461-469.
| Response to Comment on Peterson et al.
| 
| Nuding, A. and S. Hampton. 2012. Investigating human impacts on stream ecology: locally and nationally. Teaching Issues and Experiments in Ecology 8 [online]3:art116.
| 
| Scheef, L.P., D.E. Pendleton, S.E. Hampton, S.L. Katz, E.E. Holmes, M.D. Scheuerell, and D.G. Johns. 2012. Assessing marine plankton community structure from long-term monitoring data with multivariate autoregressive (MAR) models: a comparison of fixed station vs. spatially distributed sampling data. Limnology & Oceanography: Methods 10: 54-64.
| 
| Hampton, S.E., and J.N. Parker. 2011. Collaboration and productivity in scientific synthesis. BioScience 61: 900-910.
| 
| Katz, S.L., S.E. Hampton, L.R. Izmest’eva, and M.V. Moore. 2011. Long-distance climate teleconnection deciphered through non-stationary long-term environmental data in Siberia. PLoS ONE 6(2): e14688. doi:10.1371/journal.pone.0014688
| 
| Hampton, S.E., S.C. Fradkin, P.R. Leavitt, and E.E. Rosenberger. 2011. Disproportionate importance of nearshore habitat for the food web of a deep oligotrophic lake. Marine & Freshwater Research 62: 350-358.
| 
| Pace, M.L., S.E. Hampton, K.E. Limburg, E.M. Bennett, E.M. Cook, A.E. Davis, J.M. Grove, K.Y. Kaneshiro, S.L. LaDeau, G.E. Likens, D. McKnight, D.C. Richardson, and D.L. Strayer. 2010. Communicating with the public: opportunities and rewards for individual ecologists. Frontiers in Ecology and the Environment 6(8): 292-298.
| 
| Saha, N., G. Aditya, A. Bal, G.K. Saha, and S.E. Hampton. 2010. Opportunistic foraging by heteropteran mosquito predators. Aquatic Ecology 44(1): 167-176.
| 
| Moore, M.V., S.E. Hampton, L.R. Izmest’eva, E.A. Silow, E.V. Peshkova, and B.K. Pavlov. 2009. Climate change and the world’s “Sacred Sea” – Lake Baikal, Siberia.BioScience 59(5): 405-417.
| Representative Press: CNN
| 
| Hampton, S.E., L.R. Izmest’eva, M.V. Moore, S.L. Katz, and E.A. Silow. 2008. Sixty years of environmental change in the world’s largest freshwater lake – Lake Baikal, Siberia. Global Change Biology 14: 1947-1958.
| Representative Press: New York Times
| 
| Rosenberger, E.E., S.E. Hampton, S.C. Fradkin, B.P. Kennedy. 2008. Effects of shoreline development on the nearshore environment in large deep oligotrophic lakes. Freshwater Biology 53(8): 1673-1691.
| 
| Hampton, S.E., M.D. Scheuerell, and D.E. Schindler. 2006. Coalescence in the Lake Washington story: interaction strengths in a planktonic food web. Limnology & Oceanography 51: 2042-2051.
| 
| Izmest’eva, L., M.V. Moore, and S.E. Hampton. 2006. Seasonal dynamics of common phytoplankton in Lake Baikal. Proceedings of Samara Russian Academy of Sciences Scientific Centre 8(3): 191-196.
| 
| Hampton, S.E., and D.E. Schindler. 2006. Empirical evaluation of observation scale effects in community time series. Oikos 113: 424-439.
| 
| Hampton, S.E., P. Romare, and D.E. Seiler. 2006. Environmentally controlled Daphnia spring increase with implications for sockeye salmon fry in Lake Washington, USA. Journal of Plankton Research 28: 399-406.
| 
| Hampton, S.E. 2005. Increased niche differentiation between two Conochilus species over 33 years of climate change and food web alteration. Limnology & Oceanography 50: 421-426.
| 
| Jeppesen, E., et al. (29 contributors). 2005. Lake responses to reduce nutrient loading – an analysis of contemporary long-term data from 35 case studies. Freshwater Biology 50: 1747-1771.
| 
| Hampton, S.E. 2004. Habitat overlap of enemies: temporal patterns and the role of spatial complexity. Oecologia 138: 475-484.
| 
| Hampton, S.E., and I.C. Duggan. 2003. Diel habitat shifts of macrofauna in a fishless pond. Marine & Freshwater Research 54(7): 797-805.
| 
| Hampton, S.E., and N.A. Friedenberg. 2002. Nocturnal increases in the use of near-surface water by pond animals. Hydrobiologia 477: 171-179.
| 
| Gilbert, J.J., and S.E. Hampton. 2001. Diel vertical migrations of zooplankton in a shallow, fishless pond: a possible avoidance-response cascade induced by notonectids. Freshwater Biology 46(5): 611-621.
| 
| Hampton, S.E., and J.J. Gilbert. 2001. Observations of insect predation on rotifers. Hydrobiologia 446/447: 115-121.
| 
| Hampton, S.E., J.J. Gilbert, and C.W. Burns. 2000. Direct and indirect effects of juvenile Buenoa macrotibialis (Hemiptera: Notonectidae) on the zooplankton of a shallow fishless pond. Limnology & Oceanography 45(4): 1006-1012.
| 
| Hampton, S.E. 1998. Morphotype-specific predation in the trimorphic rotifer Asplanchna silvestrii. Hydrobiologia 387/388: 437-444.
| 
| Hampton, S.E., and P.L. Starkweather. 1998. Differences in predation among morphotypes of the rotifer Asplanchna silvestrii. Freshwater Biology 40(4): 595-605.

## Non Peer Reviewed

| Meyer, M. F., M. R. Brousil, A. N. Cramer, B. P. Lanouette, J. C. Padowski, and S. E. Hampton. In press. The Global Lake Area, Climate, and Population Dataset: A New Tool for Addressing Critical Limnological Questions. Limnology and Oceanography Bulletin doi.org/10.1002/lob.10406
| 
| Hampton, S. E., S. M. Powers, S. P. Devlin, and D. M. McKnight. 2020. Big questions, few answers about what happens under lake ice. Eos 101: doi.org/10.1029/2020EO146256.
| 
| Hampton, S.E. (with B.C. Clark). 2020. A natural understanding. Washington MagazineSummer 2020.
| 
| Pollard, A.I., Hampton, S.E., Leech, D.M. 2018. The promise and potential of continental‐scale limnology using the U.S. Environmental Protection Agency’s National Lakes Assessment. Limnology & Oceanography Bulletin. DOI 10.1002/lob.10238
| 
| Hampton, S.E., et al. 2017. Best practices for virtual participation in meetings: experiences from synthesis centers. The Bulletin of the Ecological Society of America 98: 57–63. doi:10.1002/bes2.1290.
| 
| Hampton, S.E., Gray, D., Sharma, S., and O’Reilly, C.M. 2016. Rapid and highly variable warming of lake surface waters around the globe. Mountain Views Chronicle10(1): 5-8.
| 
| Powers, S.M., and S.E. Hampton. 2016. Winter limnology as a new frontier. Limnology and Oceanography Bulletin 25(4): 103–108.
| 
| Hampton, S.E. and E.H. Stanley. 2013. Long-term perspectives on lake science and management. Limnology and Oceanography Bulletin 22(3): 74-75.
| 
| Hampton, S.E., C.A. Strasser, and J.J. Tewksbury. 2013. Growing Pains: Taking Ecology into the 21st Century. BioScience 63(2): 69-71. doi:10.1525/bio.2013.63.2.2.
| 
| Hampton, S.E., J.J. Tewksbury, and C.A. Strasser. 2012. Ecological data in the Information Age. Frontiers in Ecology and the Environment 10 (2): 59.
| 
| Hampton, S.E., and T.A. Wheeler. 2011. Fostering the rebirth of natural history. Biology Letters. Online Early 31 Aug 2011.
| 
| Schindler, D.E., and S.E. Hampton. 2004. Book review – Regime Shifts in Lake Ecosystems: Patterns and Processes by Stephen R. Carpenter. Quarterly Review of Biology 79(4): 445.
| 
| Wilson, K.A. and S.E. Hampton. 2004. Teaching tips for new professors. Bulletin of the Ecological Society of America 85(2): 56-64.